name: Deploy
on:
  workflow_dispatch:
    inputs:
      release:
        description: 'Release'
        required: true
      environment:
        description: 'Environment'
        required: true
        default: 'Test'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Deploying ${GITHUB_REF#refs/heads/} or ${GITHUB_REF##*/} or ${{ github.event.inputs.release }} to ${{ github.event.inputs.environment }}!"
