name: Deploy
on:
  workflow_dispatch:
    inputs:
      release:
        description: 'Release'
        required: true
      environment:
        description: 'Environment'
        required: true
        default: 'Test'

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Deploying ${{ github.event.inputs.release }} to ${{ github.event.inputs.environment }}!"
