name: Deploy
on:
  workflow_dispatch:
    inputs:
      release:
        description: 'Release'
        required: true
      environment:
        description: 'Environment'
        required: true
        default: 'Test'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy
      run: echo Deploying $GITHUB_REF_NAME or ${{ github.event.inputs.release }} to ${{ github.event.inputs.environment }}!
