name: Deploy
on:
  workflow_dispatch:
    inputs:
      release:
        description: 'Release'
        required: true
      environment:
        description: 'Environment'
        required: true
        default: 'Test'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Extract branch name
      id: extract_branch
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"     
    - name: Deploy
      run: echo "Deploying ${{ steps.extract_branch.outputs.branch }} or ${{ github.event.inputs.release }} to ${{ github.event.inputs.environment }}!"
