name: build docker

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v2
    - name: Login to docker
      uses: docker/login-action@v1
      with:
         username: ${{ github.actor }}
         password: ${{ secrets.GITHUB_TOKEN }}
         registry: docker.pkg.github.com
    - name: Push to Docker Hub
      uses: docker/build-push-action@v2
      with:
        push: true
        repository: anderssonpeter/test-actions
        tag_with_ref: true

